### ISSUE TITLE
Error loading tip.html in sample

### ISSUE THREAD

**Issue by KarthickSelvamGE** [rrrene/tipsy.hovercard#3]

**Comment by rrrene** [comment]
I guess this is happening when viewing `sample/index.html` in a browser?

You most likely experience an error like this:

```
XMLHttpRequest cannot load file:///home/[...]/tipsy.hovercard/sample/tip.html. Origin null is not allowed by Access-Control-Allow-Origin.
```

This occurs because the file is not served via a web server. As far as I can tell, the only proper solution would be to exclude the sample from `index.html` ...
