### ISSUE TITLE
Tipsy's original delayIn doesn't work with hovercard

### ISSUE THREAD

**Issue by sparanoid** [rrrene/tipsy.hovercard#4]
Any idea how to support it? Thanks.

**Comment by rrrene** [comment]
Unfortunately, tipsy.hovercard doesn't support the "delayIn" and "delayOut" options out-of-the-box.

One way to get the same result would be to use [HoverIntent](http://cherne.net/brian/resources/jquery.hoverIntent.html) with tipsy.hovercard.

**Comment by sparanoid** [comment]
@rrrene I got it, I'm using HoverIntent to delay popup, thanks!

**Comment by rrrene** [comment]
FYI: I just included `delayIn` and `delayOut` options in the last release!
