### ISSUE TITLE
hovercard's option not working

### ISSUE THREAD

**Issue by SocialfiPanda** [rrrene/tipsy.hovercard#5]
I pass in arguments as follows and the whole tipsy just broke down:

$(xxxx).tipsy({ 
                      gravity: 'w', 
                      html: true,
                      title: function(d) {})
});

Is this a bug in the hovercard library or I am passing the arguments in a wrong way? Thanks.

**Comment by SocialfiPanda** [comment]
I mean
$(xxxx).tipsyHoverCard

**Comment by rrrene** [comment]
Your parameters seem correct ...

Could you provide an error description from the console?

**Comment by SocialfiPanda** [comment]
Sure.

Uncaught TypeError: Cannot read property 'options' of undefined... (the error comes from following lines, and looks like from line 3 below:)

function setHideTimeout(ele) {
      clearHideTimeout(ele);
      var options = ele.tipsy(true).options;
      var timeoutId = setTimeout(function() { $(ele).tipsy('hide'); }, options.hideDelay);
      ele.data('timeoutId', timeoutId);
    }

If I manually changed function below to following, there are no more errors, but the tipsy does not show up:
function setHideTimeout(ele) {
      clearHideTimeout(ele);
      var timeoutId = setTimeout(function() { $(ele).tipsy('hide'); }, 300);
      ele.data('timeoutId', timeoutId);
    }

Thank you so much in advance!!!!

**Comment by rrrene** [comment]
Have you included the tipsy+jquery scripts _before_ the tipsy.hovercard script? 

You know, like

```
<script src="javascripts/jquery.js" type="text/javascript"></script>
<script src="javascripts/jquery.tipsy.js" type="text/javascript"></script>
<script src="javascripts/jquery.tipsy.hovercard.js" type="text/javascript"></script>
```

**Comment by SocialfiPanda** [comment]
yep. should I also include jquery.cluetip.js and jquery.hoverIntent.js? I tried both with and without including these two js files but all failed.

This is what I have:
                <script type="text/javascript" src="js/jquery-1.8.3.min.js"></script>
        <script type="text/javascript" src="js/jquery.tipsy.js"></script>
        <script type="text/javascript" src="js/jquery.tipsy.hovercard.js"></script>
        <script type="text/javascript" src="js/jquery.hoverIntent.js"></script>
        <script type="text/javascript" src="js/jquery.cluetip.js"></script>

(I tried both with and without last two lines) Thanks!

**Comment by SocialfiPanda** [comment]
```
            <script type="text/javascript" src="js/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="js/jquery.tipsy.js"></script>
    <script type="text/javascript" src="js/jquery.tipsy.hovercard.js"></script>
    <script type="text/javascript" src="js/jquery.hoverIntent.js"></script>
    <script type="text/javascript" src="js/jquery.cluetip.js"></script>
```

**Comment by rrrene** [comment]
Never mind. It was my fault! :hushed:

The latest commits should fix your problem, please redownload `jquery.tipsy.hovercard.js` and see if it works now:

https://github.com/rrrene/tipsy.hovercard/blob/master/lib/jquery.tipsy.hovercard.js

**Comment by SocialfiPanda** [comment]
Thanks! But I still got the same bug. This is my test code:

```
<div id='test'></div>
<link href="css/tipsy.css" rel="stylesheet">
<link href="css/tipsy.hovercard.css" rel="stylesheet">
<script type="text/javascript" src="js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="js/jquery.tipsy.js"></script>
<script type="text/javascript" src="js/jquery.tipsy.hovercard.js"></script>
<script type="text/javascript">
function fillDivWithData(selectorElement, data) {
    selectorElement.empty();
    selectorElement.append($('<p class="tipsy">' + data + '</p>'));
    $(".tipsy").tipsyHoverCard({gravity: 'w', html: true, fallback: "<div>Tipsy Test</div>"});
}
fillDivWithData($('#test'), 'Hello world');
</script>
```

If I change tipsyHoverCard to tipsy in the fillDivWithData() the tipsy works fine. Will really appreciate it if you can help me out!

**Comment by SocialfiPanda** [comment]
and the 2.0.3 version of jquery also does not help my issue.

**Comment by rrrene** [comment]
Ok, there are two problems with your code:
1. You use the `tipsy` class for your container, but that is the same class the actual tipsy-tooltip uses.
2. You use a block-level p element which automatically has 100% width, therefore the tooltip with gravity 'w' is positioned right of the element outside the viewport.

Try the following code, using another class and an inline element:

```
<div id='test'></div>
<script type="text/javascript">
  function fillDivWithData(selectorElement, data) {
      selectorElement.empty();
      selectorElement.append($('<span class="hovercard">' + data + '</span>'));
      $("span.hovercard").tipsyHoverCard({gravity: 'w', html: true, fallback: "<div>Tipsy Test</div>"});
  }
  fillDivWithData($('#test'), 'Hello world');
</script>
```

Also: Definitely use Jquery 2.0.3 when building something new!

**Comment by SocialfiPanda** [comment]
Hmm... using your code above still reproduce the same bug. This is the complete testing code using your code above (thanks!!!):

```
<div id='test'></div>
<link href="css/tipsy.css" rel="stylesheet">
<link href="css/tipsy.hovercard.css" rel="stylesheet">
<script type="text/javascript" src="js/jquery-2.0.3.min.js"></script>
<script type="text/javascript" src="js/jquery.tipsy.js"></script>
<script type="text/javascript" src="js/jquery.tipsy.hovercard.js"></script>
<script type="text/javascript">
  function fillDivWithData(selectorElement, data) {
      selectorElement.empty();
      selectorElement.append($('<span class="hovercard">' + data + '</span>'));
      $("span.hovercard").tipsyHoverCard({gravity: 'w', html: true, fallback: "<div>Tipsy Test</div>"});
  }
  fillDivWithData($('#test'), 'Hello world');
</script>
```

**Comment by rrrene** [comment]
I am afraid that I can not reproduce your bug.

If I paste your code into an empty html file and point the `<script>` tags to my local copies of JQuery, Tipsy and tipsy.hovercard it just works. Tested in Firefox and Chrome.

**Comment by SocialfiPanda** [comment]
Thanks! I found the problem is I am not using the lastest version of tipsy.
