### ISSUE TITLE
How do I change the align of the html element?

### ISSUE THREAD

**Issue by hurtworldmap** [rrrene/tipsy.hovercard#8]
Hello, thanks for this awesome script.

How can I change the way the html content align?
Right now it looks like the element is centered below the element that call it.

I want to make the element that are called to appear a little to the right below .

**Comment by rrrene** [comment]
You can "move" the hovercard my applying a margin. Try the following CSS and you will see what I mean:

```
.tipsy-hovercard {
  margin-left: 60px;
  margin-top: -20px;
}
```

**Comment by hurtworldmap** [comment]
Thanks, it worked!

I have a suggestion, it is possible to make the tooltip content follow the mouse?
Example: http://jsfiddle.net/qTip2/z630aya5/

**Comment by rrrene** [comment]
I' am glad it worked!

Following the mouse is unfortunately not something this plugin will support :(
